name: ci
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.6"
          cache: npm
      - run: npm ci
      - run: npm run ci
  speech-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: speech-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements-ci.txt
      - run: pytest
        env:
          SPEECH_API_MOCK: "1"
